import type { KeeperAdvisorRosterPlayer } from './keeperAdvisor';

export type Position = 'C' | 'L' | 'R' | 'D' | 'G';

export interface Player {
  id: number;
  full_name: string;
  positionCode: Position;
  headshot: string;
  sweaterNumber: number;

  // Season stats
  gamesPlayed: number;
  goals: number;
  assists: number;
  points: number;
  powerPlayPoints: number;
  shorthandedPoints: number;
  shots: number;
  avgToi: string;

  // Fantasy
  fantasyPoints: number;
  season_ppg: number;

  // Last 5 games
  last5_goals: number;
  last5_assists: number;
  last5_points: number;
  last5_fantasyPoints: number;

  // Scores
  weighted_score: number;
  ml_score: number;
  final_score: number;
  cooling_score: number;

  // Status
  rostered: boolean;
}

// One SHAP factor behind a draft projection. A positive value pushed the
// ranking up, negative pulled it down — the sign is what drives the colour.
export interface DraftFactor {
  label: string;
  value: number;
}

// Season-level draft projection row (from main.py draft -> api_export.py).
// Distinct shape from Player: no live/last-5 stats, projection fields instead.
// confidence/factors come from the model; summary is batch-generated by Claude
// and is display-only. All three are nullable/empty when not yet generated.
export interface DraftPlayer {
  id: number;
  full_name: string;
  positionCode: Position;
  headshot: string;
  age: number | null;
  gamesPlayed: number;
  last_fpPerGame: number;
  projected_fpPerGame: number;
  projected_total: number;
  delta_vs_last: number;
  vorp: number | null;
  projected_gp: number | null;
  confidence: number | null;
  factors: DraftFactor[];
  stats: DraftStat[];
  summary: string | null;
}

// Last season's actual production, pre-formatted by api_export.py. Skaters and
// goalies share no columns, so the shape is label/value pairs and the board
// renders whatever it is handed. Display only — never a model input.
export interface DraftStat {
  label: string;
  value: string;
}

// League slot rules, shipped by api_export.py::_draft_roster_rules so the board
// does not keep its own copy of numbers keeper.py owns. Absent in snapshots
// exported before they existed; the board falls back to its own constants.
export interface DraftRosterRules {
  starting_slots: Record<Position, number>;
  max_by_position: Record<Position, number>;
  util_slots: number;
  roster_slots: Record<string, number>;
}

export interface KeeperRecommendation {
  id: number | null;
  full_name: string;
  positionCode: Position;
  headshot: string | null;
  keeper_rank: number;
  assigned_round: number;
  pick_cost: number;
  raw_keeper_value: number;
  net_keeper_value: number;
  last_fpPerGame: number;
  gamesPlayed: number;
  projected_fpPerGame: number;
  projected_total: number;
  confidence: number | null;
  // Multi-year keeper valuation. Null on a board built without season history
  // (a fresh clone), so every read has to be guarded.
  horizon_keeper_value: number | null;
  horizon_multiplier: number | null;
  horizon_pick_cost: number | null;
  horizon_breakdown: HorizonYear[] | null;
}

export interface HorizonYear {
  year: number;
  discount: number;
  survival: number;
  aging: number;
  value: number;
}

export interface KeeperSection {
  season: string;
  advisor_ready: boolean;
  advisor_context_id: string | null;
  advisor_generated_at: string | null;
  advisor_roster: KeeperAdvisorRosterPlayer[];
  recommendations: KeeperRecommendation[];
}

export interface PickupRecommendation extends Player {
  rank: number;
}

export interface CoolingCandidate extends Player {
  rank: number;
}
