export type Position = 'C' | 'L' | 'R' | 'D';

export interface Player {
  id: number;
  full_name: string;
  positionCode: Position;
  headshot: string;
  sweaterNumber: number;

  // Season stats
  gamesPlayed: number;
  goals: number;
  assists: number;
  points: number;
  plusMinus: number;
  powerPlayPoints: number;
  shorthandedPoints: number;
  shots: number;
  avgToi: string;

  // Fantasy
  fantasyPoints: number;
  season_ppg: number;

  // Last 5 games
  last5_goals: number;
  last5_assists: number;
  last5_points: number;
  last5_fantasyPoints: number;

  // Scores
  weighted_score: number;
  ml_score: number;
  final_score: number;
  cooling_score: number;

  // Status
  rostered: boolean;
}

// One SHAP factor behind a draft projection. A positive value pushed the
// ranking up, negative pulled it down — the sign is what drives the colour.
export interface DraftFactor {
  label: string;
  value: number;
}

// Season-level draft projection row (from main.py draft -> api_export.py).
// Distinct shape from Player: no live/last-5 stats, projection fields instead.
// confidence/factors come from the model; summary is batch-generated by Claude
// and is display-only. All three are nullable/empty when not yet generated.
export interface DraftPlayer {
  id: number;
  full_name: string;
  positionCode: Position;
  headshot: string;
  age: number | null;
  gamesPlayed: number;
  last_fpPerGame: number;
  projected_fpPerGame: number;
  projected_total: number;
  delta_vs_last: number;
  confidence: number | null;
  factors: DraftFactor[];
  summary: string | null;
}

export interface KeeperRecommendation {
  id: number | null;
  full_name: string;
  positionCode: Position;
  headshot: string | null;
  keeper_rank: number;
  assigned_round: number;
  pick_cost: number;
  raw_keeper_value: number;
  net_keeper_value: number;
  last_fpPerGame: number;
  gamesPlayed: number;
  projected_fpPerGame: number;
  projected_total: number;
  confidence: number | null;
}

export interface KeeperSection {
  season: string;
  summary: string | null;
  summary_generated_at: string | null;
  recommendations: KeeperRecommendation[];
}

export interface PickupRecommendation extends Player {
  rank: number;
}

export interface CoolingCandidate extends Player {
  rank: number;
}
