import { NextResponse } from 'next/server';
import { readFileSync, existsSync, statSync } from 'fs';
import { join } from 'path';

// Path to the JSON data file generated by Python
const DATA_PATH = join(process.cwd(), '..', 'data', 'processed', 'frontend_data.json');

export async function GET() {
  try {
    if (!existsSync(DATA_PATH)) {
      return NextResponse.json(
        {
          error: 'Data not found. Run: python api_export.py',
          pickups: [],
          cooling: [],
          draft: [],
          keeper: null,
        },
        { status: 404 }
      );
    }

    const data = JSON.parse(readFileSync(DATA_PATH, 'utf-8'));
    const stats = statSync(DATA_PATH);
    const exportedAt = Date.parse(data.generated_at);
    const ageMs = Number.isNaN(exportedAt)
      ? Date.now() - stats.mtimeMs
      : Date.now() - exportedAt;
    const ageHours = Math.round(ageMs / (1000 * 60 * 60) * 10) / 10;

    return NextResponse.json({
      ...data,
      keeper: data.keeper ?? null,
      dataAge: `${ageHours}h ago`,
    });
  } catch (error) {
    console.error('Error loading player data:', error);
    return NextResponse.json(
      { error: 'Failed to load data', pickups: [], cooling: [], draft: [], keeper: null },
      { status: 500 }
    );
  }
}
